// Builds the Adulted screens from web/app.html plus the shared data and prompts.
// Outputs:
//   server/web/index.html        the web app the server shows at /app
//   app/src/page.generated.js    the same page, bundled inside the phone app
//   dist/adulted.html           a standalone copy (for previews in Claude)
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const read = (p) => fs.readFileSync(path.join(root, p), "utf8");
const write = (p, text) => { fs.mkdirSync(path.dirname(path.join(root, p)), { recursive: true }); fs.writeFileSync(path.join(root, p), text); };

const page = read("web/app.html");
const shared = ["shared/data.js", "shared/prompts.js", "web/illustrations.js"].map(read);
for (const code of shared) if (/<\/script/i.test(code)) throw new Error("Shared code must not contain a closing script tag.");
if (!page.includes("<!--@SHARED-->")) throw new Error("web/app.html is missing the <!--@SHARED--> marker.");

const fragment = page.replace("<!--@SHARED-->", shared.map((c) => `<script>\n${c}\n</script>`).join("\n"));
const reset = "<style>html,body{margin:0;background:#F1F4F7}img{max-width:100%}[hidden]{display:none!important}</style>";
const head = (extra) => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#F1F4F7">${extra}${reset}</head><body>\n`;
const tail = "\n</body></html>\n";

const phone = "// Generated by scripts/build-web.js. Do not edit; change web/app.html or shared/ and rebuild.\nexport default " + JSON.stringify(head("") + fragment + tail) + ";\n";
if (process.argv.includes("--check")) {
  const current = fs.existsSync(path.join(root, "app/src/page.generated.js")) ? read("app/src/page.generated.js") : "";
  if (current !== phone) { console.error("app/src/page.generated.js is out of date. Run: node scripts/build-web.js"); process.exit(1); }
  console.log("Phone app screens are up to date.");
  process.exit(0);
}
// Step photos and videos: served by the website at /app/media, and loaded by the phone app from there too.
const mediaSrc = path.join(root, "web/media"), mediaOut = path.join(root, "server/web/media");
if (fs.existsSync(mediaSrc)) { fs.mkdirSync(mediaOut, { recursive: true }); for (const f of fs.readdirSync(mediaSrc)) fs.copyFileSync(path.join(mediaSrc, f), path.join(mediaOut, f)); }
write("server/web/index.html", head('<link rel="icon" href="/favicon.png"><script>window.ADULTED_API="/api";</script>') + fragment + tail);
write("app/src/page.generated.js", phone);
write("dist/adulted.html", fragment);
console.log(`Built the web app (${Math.round(fragment.length / 1024)} KB): server/web/index.html, app/src/page.generated.js, dist/adulted.html`);
